//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunicationSalon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientService
    {
        public int Id { get; set; }
        public int ServiceId { get; set; }
        public int ClientId { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<bool> Accept { get; set; }
        public Nullable<bool> Disabled { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual User User { get; set; }
    }
}
